### ISSUE TITLE
reflection error

### ISSUE THREAD

**Issue by chihyangscience** [owainlewis/clojure-mail#29]
Hi there,

I used this lib [io.forward/clojure-mail "1.0"] in my test, it works fine on my local box, but when I run in in jenkins, there is a strange reflection error, any clue why it happened?

Thanks!

18:40:02,623 ERROR [SoapUI] An error occurred [No matching field found: getDefaultFolder for class java.lang.Character], see error log for details
java.lang.IllegalArgumentException: No matching field found: getDefaultFolder for class java.lang.Character
	at clojure.lang.Reflector.getInstanceField(Reflector.java:271)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:315)
	at clojure_mail.core$open_folder.invoke(core.clj:136)
	at clojure_mail.core$search_inbox.invoke(core.clj:207)
	at everbridge.mail_service$get_mail_by_title.invoke(mail_service.clj:145)
	at everbridge.qa$_EmailsearchEmail.invoke(qa.clj:130)
	at everbridge.qa.EmailsearchEmail(Unknown Source)
	at everbridge.qa$EmailsearchEmail.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at Script1.run(Script1.groovy:4)
	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:92)
	at com.eviware.soapui.support.scripting.groovy.SoapUIProGroovyScriptEngineFactory$SoapUIProGroovyScriptEngine.run(SourceFile:79)
	at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:138)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStep(AbstractTestCaseRunner.java:213)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestCaseRunner.runCurrentTestStep(WsdlTestCaseRunner.java:47)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:139)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:47)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestRunner.run(AbstractTestRunner.java:129)
	at java.util.concurrent.Executors

**Comment by chihyangscience** [comment]
sorry, it is different issue, has been fixed, however, I suggest during login email, do not capture the exception, or re-thrown the exception, return a different object make debug difficult.
***************
 (catch AuthenticationFailedException e
         (format "Invalid credentials %s : %s" email pass)))))
**********************
